In [1]:
import pickle
from pre_train import *

In [3]:
sabdab = load_data("../Transformer4Ab/data/data_list.pkl")
len(sabdab)

5380

In [4]:
sabdab[0]

{'pdb': '7t17',
 'Hchain': 'J',
 'Lchain': 'K',
 'Achain': ['C'],
 'Hseq': {'J': [{'name': 'GLN',
    'abbr': 'Q',
    'pos': array([[ 57.69 , -27.721, 213.695],
           [ 56.713, -27.938, 214.755],
           [ 56.848, -26.882, 215.848],
           [ 57.955, -26.464, 216.188]], dtype=float32)},
   {'name': 'VAL',
    'abbr': 'V',
    'pos': array([[ 55.708, -26.454, 216.394],
           [ 55.725, -25.461, 217.46 ],
           [ 56.083, -26.137, 218.776],
           [ 55.473, -27.138, 219.173]], dtype=float32)},
   {'name': 'GLN',
    'abbr': 'Q',
    'pos': array([[ 57.085, -25.589, 219.46 ],
           [ 57.561, -26.15 , 220.715],
           [ 57.666, -25.045, 221.754],
           [ 58.003, -23.902, 221.438]], dtype=float32)},
   {'name': 'LEU',
    'abbr': 'L',
    'pos': array([[ 57.37 , -25.4  , 223.002],
           [ 57.438, -24.472, 224.121],
           [ 58.445, -24.994, 225.135],
           [ 58.476, -26.192, 225.431]], dtype=float32)},
   {'name': 'GLN',
    'abbr': 'Q',
    'pos': array([[ 59.266, -24.09 , 225.664],
           [ 60.31 , -24.454, 226.618],
           [ 60.226, -23.5  , 227.8  ],
           [ 60.546, -22.315, 227.665]], dtype=float32)},
   {'name': 'GLU',
    'abbr': 'E',
    'pos': array([[ 59.781, -24.01 , 228.944],
           [ 59.746, -23.212, 230.159],
           [ 61.073, -23.322, 230.902],
           [ 61.626, -24.41 , 231.08 ]], dtype=float32)},
   {'name': 'SER',
    'abbr': 'S',
    'pos': array([[ 61.582, -22.173, 231.34 ],
           [ 62.857, -22.111, 232.039],
           [ 62.79 , -20.989, 233.063],
           [ 61.865, -20.174, 233.038]], dtype=float32)},
   {'name': 'GLY',
    'abbr': 'G',
    'pos': array([[ 63.755, -20.968, 233.977],
           [ 63.815, -19.938, 234.984],
           [ 64.451, -20.424, 236.269],
           [ 65.103, -21.472, 236.311]], dtype=float32)},
   {'name': 'PRO',
    'abbr': 'P',
    'pos': array([[ 64.278, -19.66 , 237.348],
           [ 64.8  , -20.079, 238.656],
           [ 63.906, -21.149, 239.263],
           [ 62.786, -20.871, 239.703]], dtype=float32)},
   {'name': 'GLY',
    'abbr': 'G',
    'pos': array([[ 64.403, -22.387, 239.281],
           [ 63.618, -23.482, 239.824],
           [ 63.576, -23.497, 241.338],
           [ 62.676, -24.095, 241.932]], dtype=float32)},
   {'name': 'LEU',
    'abbr': 'L',
    'pos': array([[ 64.542, -22.846, 241.982],
           [ 64.589, -22.742, 243.436],
           [ 64.326, -21.293, 243.812],
           [ 65.034, -20.392, 243.349]], dtype=float32)},
   {'name': 'VAL',
    'abbr': 'V',
    'pos': array([[ 63.313, -21.07 , 244.646],
           [ 62.936, -19.731, 245.074],
           [ 62.766, -19.719, 246.587],
           [ 62.523, -20.748, 247.222]], dtype=float32)},
   {'name': 'LYS',
    'abbr': 'K',
    'pos': array([[ 62.9  , -18.526, 247.162],
           [ 62.745, -18.271, 248.587],
           [ 61.279, -18.031, 248.923],
           [ 60.478, -17.737, 248.027]], dtype=float32)},
   {'name': 'PRO',
    'abbr': 'P',
    'pos': array([[ 60.905, -18.17 , 250.195],
           [ 59.526, -17.864, 250.591],
           [ 59.283, -16.361, 250.593],
           [ 60.104, -15.577, 251.073]], dtype=float32)},
   {'name': 'SER',
    'abbr': 'S',
    'pos': array([[ 58.134, -15.964, 250.043],
           [ 57.795, -14.553, 249.885],
           [ 58.442, -13.92 , 248.655],
           [ 58.282, -12.718, 248.418]], dtype=float32)},
   {'name': 'GLN',
    'abbr': 'Q',
    'pos': array([[ 59.161, -14.71 , 247.865],
           [ 59.824, -14.209, 246.669],
           [ 58.852, -14.239, 245.49 ],
           [ 57.688, -14.632, 245.611]], dtype=float32)},
   {'name': 'THR',
    'abbr': 'T',
    'pos': array([[ 59.332, -13.815, 244.323],
           [ 58.533, -13.767, 243.103],
           [ 59.234, -14.601, 242.039],
           [ 60.253, -14.176, 241.482]], dtype=float32)},
   {'name': 'LEU',
    'abbr': 'L',
    'pos': array([[ 58.696, -15.787, 241.765],
           [ 59.257, -16.638, 240.725],
           [ 58.873, -16.106, 239.351],
           [ 57.764, -15.607, 239.147]], dtype=float32)},
   {'name': 'SER',
    'abbr': 'S',
    'pos': array([[ 59.801, -16.21 , 238.403],
           [ 59.581, -15.722, 237.044],
           [ 60.013, -16.813, 236.077],
           [ 61.211, -17.068, 235.92 ]], dtype=float32)},
   {'name': 'LEU',
    'abbr': 'L',
    'pos': array([[ 59.044, -17.455, 235.431],
           [ 59.312, -18.487, 234.444],
           [ 59.057, -17.93 , 233.052],
           [ 58.029, -17.297, 232.794]], dtype=float32)},
   {'name': 'THR',
    'abbr': 'T',
    'pos': array([[ 60.007, -18.168, 232.154],
           [ 59.914, -17.711, 230.778],
           [ 59.731, -18.916, 229.871],
           [ 60.508, -19.874, 229.928]], dtype=float32)},
   {'name': 'CYS',
    'abbr': 'C',
    'pos': array([[ 58.688, -18.868, 229.048],
           [ 58.397, -19.904, 228.065],
           [ 58.821, -19.369, 226.704],
           [ 58.2  , -18.438, 226.177]], dtype=float32)},
   {'name': 'ALA',
    'abbr': 'A',
    'pos': array([[ 59.886, -19.943, 226.156],
           [ 60.319, -19.624, 224.807],
           [ 59.567, -20.493, 223.808],
           [ 59.239, -21.651, 224.081]], dtype=float32)},
   {'name': 'VAL',
    'abbr': 'V',
    'pos': array([[ 59.297, -19.921, 222.638],
           [ 58.491, -20.569, 221.612],
           [ 59.33 , -20.73 , 220.353],
           [ 60.023, -19.799, 219.93 ]], dtype=float32)},
   {'name': 'SER',
    'abbr': 'S',
    'pos': array([[ 59.265, -21.92 , 219.76 ],
           [ 59.917, -22.198, 218.492],
           [ 58.855, -22.598, 217.478],
           [ 57.942, -23.373, 217.776]], dtype=float32)},
   {'name': 'GLY',
    'abbr': 'G',
    'pos': array([[ 58.99 , -22.06 , 216.268],
           [ 58.007, -22.301, 215.232],
           [ 56.785, -21.414, 215.288],
           [ 55.782, -21.726, 214.639]], dtype=float32)},
   {'name': 'GLY',
    'abbr': 'G',
    'pos': array([[ 56.834, -20.319, 216.043],
           [ 55.692, -19.433, 216.161],
           [ 56.029, -18.207, 216.976],
           [ 57.16 , -18.035, 217.443]], dtype=float32)},
   {'name': 'SER',
    'abbr': 'S',
    'pos': array([[ 55.027, -17.349, 217.14 ],
           [ 55.171, -16.096, 217.87 ],
           [ 53.91 , -15.844, 218.685],
           [ 52.941, -16.604, 218.588]], dtype=float32)},
   {'name': 'ILE',
    'abbr': 'I',
    'pos': array([[ 53.929, -14.778, 219.489],
           [ 52.78 , -14.463, 220.333],
           [ 51.659, -13.82 , 219.527],
           [ 50.497, -13.829, 219.95 ]], dtype=float32)},
   {'name': 'SER',
    'abbr': 'S',
    'pos': array([[ 51.981, -13.253, 218.364],
           [ 50.992, -12.578, 217.531],
           [ 50.342, -13.491, 216.5  ],
           [ 49.851, -12.982, 215.487]], dtype=float32)},
   {'name': 'SER',
    'abbr': 'S',
    'pos': array([[ 50.31 , -14.804, 216.735],
           [ 49.83 , -15.759, 215.74 ],
           [ 48.31 , -15.713, 215.639],
           [ 47.642, -15.112, 216.485]], dtype=float32)},
   {'name': 'GLY',
    'abbr': 'G',
    'pos': array([[ 47.766, -16.346, 214.603],
           [ 46.335, -16.339, 214.376],
           [ 45.576, -17.391, 215.156],
           [ 44.343, -17.379, 215.178]], dtype=float32)},
   {'name': 'ASP',
    'abbr': 'D',
    'pos': array([[ 46.291, -18.304, 215.803],
           [ 45.656, -19.337, 216.613],
           [ 46.445, -19.545, 217.904],
           [ 46.697, -20.673, 218.332]], dtype=float32)},
   {'name': 'SER',
    'abbr': 'S',
    'pos': array([[ 46.844, -18.451, 218.547],
           [ 47.739, -18.551, 219.69 ],
           [ 47.102, -17.901, 220.909],
           [ 46.572, -16.789, 220.843]], dtype=float32)},
   {'name': 'TYR',
    'abbr': 'Y',
    'pos': array([[ 47.164, -18.625, 222.025],
           [ 46.779, -18.116, 223.333],
           [ 47.58 , -18.872, 224.381],
           [ 47.176, -19.952, 224.821]], dtype=float32)},
   {'name': 'TRP',
    'abbr': 'W',
    'pos': array([[ 48.691, -18.275, 224.808],
           [ 49.708, -18.968, 225.592],
           [ 49.25 , -19.041, 227.039],
           [ 49.097, -18.007, 227.695]], dtype=float32)},
   {'name': 'SER',
    'abbr': 'S',
    'pos': array([[ 49.058, -20.259, 227.539],
           [ 48.509, -20.471, 228.873],
           [ 49.569, -21.123, 229.744],
           [ 50.201, -22.099, 229.329]], dtype=float32)},
   {'name': 'TRP',
    'abbr': 'W',
    'pos': array([[ 49.762, -20.584, 230.942],
           [ 50.647, -21.176, 231.93 ],
           [ 49.808, -21.924, 232.957],
           [ 48.779, -21.429, 233.424]], dtype=float32)},
   {'name': 'ILE',
    'abbr': 'I',
    'pos': array([[ 50.25 , -23.131, 233.297],
           [ 49.494, -23.98 , 234.21 ],
           [ 50.395, -24.461, 235.338],
           [ 51.464, -25.032, 235.094]], dtype=float32)},
   {'name': 'ARG',
    'abbr': 'R',
    'pos': array([[ 49.973, -24.231, 236.577],
           [ 50.69 , -24.71 , 237.747],
           [ 50.418, -26.196, 237.943],
           [ 49.266, -26.639, 237.968]], dtype=float32)},
   {'name': 'GLN',
    'abbr': 'Q',
    'pos': array([[ 51.497, -26.966, 238.086],
           [ 51.409, -28.417, 238.261],
           [ 52.238, -28.778, 239.489],
           [ 53.426, -29.096, 239.371]], dtype=float32)},
   {'name': 'HIS',
    'abbr': 'H',
    'pos': array([[ 51.607, -28.728, 240.658],
           [ 52.3  , -29.046, 241.896],
           [ 52.493, -30.556, 242.011],
           [ 51.749, -31.326, 241.39 ]], dtype=float32)},
   {'name': 'PRO',
    'abbr': 'P',
    'pos': array([[ 53.486, -31.012, 242.772],
           [ 53.654, -32.455, 242.975],
           [ 52.597, -32.996, 243.924],
           [ 52.301, -32.399, 244.962]], dtype=float32)},
   {'name': 'GLY',
    'abbr': 'G',
    'pos': array([[ 52.019, -34.138, 243.557],
           [ 50.925, -34.695, 244.326],
           [ 49.568, -34.119, 243.995],
           [ 48.583, -34.458, 244.654]], dtype=float32)},
   {'name': 'LYS',
    'abbr': 'K',
    'pos': array([[ 49.489, -33.251, 242.991],
           [ 48.242, -32.635, 242.571],
           [ 48.212, -32.528, 241.053],
           [ 49.244, -32.605, 240.381]], dtype=float32)},
   {'name': 'GLY',
    'abbr': 'G',
    'pos': array([[ 47.006, -32.352, 240.516],
           [ 46.853, -32.213, 239.085],
           [ 47.254, -30.837, 238.59 ],
           [ 47.551, -29.921, 239.359]], dtype=float32)},
   {'name': 'LEU',
    'abbr': 'L',
    'pos': array([[ 47.269, -30.701, 237.265],
           [ 47.612, -29.427, 236.647],
           [ 46.458, -28.442, 236.791],
           [ 45.301, -28.757, 236.5  ]], dtype=float32)},
   {'name': 'GLU',
    'abbr': 'E',
    'pos': array([[ 46.783, -27.236, 237.253],
           [ 45.795, -26.177, 237.444],
           [ 46.286, -24.96 , 236.674],
           [ 47.445, -24.562, 236.821]], dtype=float32)},
   {'name': 'TRP',
    'abbr': 'W',
    'pos': array([[ 45.409, -24.377, 235.86 ],
           [ 45.803, -23.265, 235.004],
           [ 45.943, -21.985, 235.817],
           [ 45.03 , -21.595, 236.551]], dtype=float32)},
   {'name': 'ILE',
    'abbr': 'I',
    'pos': array([[ 47.098, -21.337, 235.689],
           [ 47.34 , -20.058, 236.347],
           [ 47.778, -19.043, 235.3  ],
           [ 48.973, -18.908, 235.01 ]], dtype=float32)},
   {'name': 'GLY',
    'abbr': 'G',
    'pos': array([[ 46.818, -18.326, 234.734],
           [ 47.097, -17.324, 233.729],
           [ 47.091, -17.886, 232.317],
           [ 47.611, -18.965, 232.033]], dtype=float32)},
   {'name': 'SER',
    'abbr': 'S',
    'pos': array([[ 46.478, -17.124, 231.414],
           [ 46.473, -17.483, 230.002],
           [ 46.441, -16.234, 229.134],
           [ 45.364, -15.712, 228.835]], dtype=float32)},
   {'name': 'ILE',
    'abbr': 'I',
    'pos': array([[ 47.613, -15.766, 228.7  ],
           [ 47.672, -14.528, 227.931],
           [ 47.323, -14.8  , 226.471],
           [ 47.471, -15.914, 225.954]], dtype=float32)},
   {'name': 'TYR',
    'abbr': 'Y',
    'pos': array([[ 46.853, -13.756, 225.796],
           [ 46.381, -13.848, 224.424],
           [ 47.349, -13.141, 223.485],
           [ 48.455, -12.756, 223.878]], dtype=float32)},
   {'name': 'TYR',
    'abbr': 'Y',
    'pos': array([[ 46.921, -12.987, 222.228],
           [ 47.741, -12.3  , 221.235],
           [ 47.783, -10.796, 221.473],
           [ 48.736, -10.128, 221.058]], dtype=float32)},
   {'name': 'SER',
    'abbr': 'S',
    'pos': array([[ 46.763, -10.244, 222.132],
           [ 46.749,  -8.827, 222.473],
           [ 47.575,  -8.504, 223.711],
           [ 47.779,  -7.319, 224.002]], dtype=float32)},
   {'name': 'GLY',
    'abbr': 'G',
    'pos': array([[ 48.05 ,  -9.513, 224.44 ],
           [ 48.863,  -9.311, 225.618],
           [ 48.162,  -9.551, 226.936],
           [ 48.772, -10.127, 227.846]], dtype=float32)},
   {'name': 'SER',
    'abbr': 'S',
    'pos': array([[ 46.908,  -9.126, 227.077],
           [ 46.152,  -9.421, 228.286],
           [ 45.418, -10.746, 228.124],
           [ 45.245, -11.247, 227.01 ]], dtype=float32)},
   {'name': 'THR',
    'abbr': 'T',
    'pos': array([[ 44.99 , -11.321, 229.247],
           [ 44.262, -12.582, 229.228],
           [ 43.585, -12.805, 230.571],
           [ 43.68 , -11.959, 231.466]], dtype=float32)},
   {'name': 'TYR',
    'abbr': 'Y',
    'pos': array([[ 42.91 , -13.943, 230.707],
           [ 42.194, -14.305, 231.923],
           [ 42.926, -15.433, 232.639],
           [ 43.491, -16.325, 231.999]], dtype=float32)},
   {'name': 'TYR',
    'abbr': 'Y',
    'pos': array([[ 42.91 , -15.385, 233.97 ],
           [ 43.585, -16.369, 234.804],
           [ 42.617, -16.915, 235.844],
           [ 41.454, -16.505, 235.91 ]], dtype=float32)},
   {'name': 'ASN',
    'abbr': 'N',
    'pos': array([[ 43.107, -17.857, 236.643],
           [ 42.318, -18.448, 237.716],
           [ 42.13 , -17.437, 238.844],
           [ 43.016, -16.597, 239.065]], dtype=float32)},
   {'name': 'PRO',
    'abbr': 'P',
    'pos': array([[ 41.011, -17.475, 239.569],
           [ 40.805, -16.488, 240.642],
           [ 41.587, -16.777, 241.909],
           [ 41.804, -15.86 , 242.713]], dtype=float32)},
   {'name': 'SER',
    'abbr': 'S',
    'pos': array([[ 42.006, -18.029, 242.122],
           [ 42.811, -18.355, 243.296],
           [ 44.228, -17.815, 243.157],
           [ 44.84 , -17.388, 244.143]], dtype=float32)},
   {'name': 'LEU',
    'abbr': 'L',
    'pos': array([[ 44.764, -17.827, 241.938],
           [ 46.053, -17.222, 241.652],
           [ 45.936, -15.804, 241.114],
           [ 46.923, -15.279, 240.588]], dtype=float32)},
   {'name': 'LYS',
    'abbr': 'K',
    'pos': array([[ 44.759, -15.182, 241.209],
           [ 44.54 , -13.823, 240.726],
           [ 45.293, -12.791, 241.556],
           [ 45.748, -11.773, 241.025]], dtype=float32)},
   {'name': 'SER',
    'abbr': 'S',
    'pos': array([[ 45.434, -13.044, 242.852],
           [ 46.126, -12.107, 243.73 ],
           [ 47.642, -12.206, 243.654],
           [ 48.307, -11.343, 244.241]], dtype=float32)},
   {'name': 'ARG',
    'abbr': 'R',
    'pos': array([[ 48.223, -13.197, 242.978],
           [ 49.673, -13.33 , 242.91 ],
           [ 50.228, -13.638, 241.527],
           [ 51.444, -13.509, 241.339]], dtype=float32)},
   {'name': 'VAL',
    'abbr': 'V',
    'pos': array([[ 49.402, -14.023, 240.561],
           [ 49.887, -14.481, 239.264],
           [ 49.793, -13.356, 238.244],
           [ 48.9  , -12.504, 238.296]], dtype=float32)},
   {'name': 'THR',
    'abbr': 'T',
    'pos': array([[ 50.734, -13.358, 237.302],
           [ 50.748, -12.4  , 236.206],
           [ 51.167, -13.143, 234.947],
           [ 52.036, -14.018, 235.005]], dtype=float32)},
   {'name': 'ILE',
    'abbr': 'I',
    'pos': array([[ 50.552, -12.797, 233.821],
           [ 50.835, -13.463, 232.552],
           [ 51.513, -12.473, 231.612],
           [ 50.854, -11.913, 230.724]], dtype=float32)},
   {'name': 'PRO',
    'abbr': 'P',
    'pos': array([[ 52.81 , -12.217, 231.776],
           [ 53.508, -11.31 , 230.859],
           [ 53.772, -11.974, 229.516],
           [ 53.87 , -13.196, 229.393]], dtype=float32)},
   {'name': 'ILE',
    'abbr': 'I',
    'pos': array([[ 53.879, -11.137, 228.488],
           [ 54.158, -11.592, 227.133],
           [ 55.169, -10.649, 226.497],
           [ 55.085,  -9.426, 226.642]], dtype=float32)},
   {'name': 'ASP',
    'abbr': 'D',
    'pos': array([[ 56.133, -11.231, 225.785],
           [ 57.147, -10.462, 225.062],
           [ 56.765, -10.508, 223.587],
           [ 56.908, -11.549, 222.937]], dtype=float32)},
   {'name': 'THR',
    'abbr': 'T',
    'pos': array([[ 56.271,  -9.381, 223.067],
           [ 55.835,  -9.331, 221.674],
           [ 57.021,  -9.304, 220.719],
           [ 56.996,  -9.949, 219.665]], dtype=float32)},
   {'name': 'SER',
    'abbr': 'S',
    'pos': array([[ 58.07 ,  -8.559, 221.071],
           [ 59.263,  -8.503, 220.238],
           [ 60.126,  -9.752, 220.348],
           [ 60.802, -10.103, 219.375]], dtype=float32)},
   {'name': 'LYS',
    'abbr': 'K',
    'pos': array([[ 60.12 , -10.428, 221.496],
           [ 60.934, -11.617, 221.705],
           [ 60.213, -12.911, 221.358],
           [ 60.877, -13.923, 221.11 ]], dtype=float32)},
   {'name': 'ASN',
    'abbr': 'N',
    'pos': array([[ 58.88 , -12.902, 221.312],
           [ 58.097, -14.102, 221.015],
           [ 58.155, -15.115, 222.156],
           [ 58.296, -16.321, 221.941]], dtype=float32)},
   {'name': 'GLN',
    'abbr': 'Q',
    'pos': array([[ 58.047, -14.618, 223.386],
           [ 58.104, -15.449, 224.578],
           [ 56.989, -15.046, 225.534],
           [ 56.442, -13.942, 225.461]], dtype=float32)},
   {'name': 'PHE',
    'abbr': 'F',
    'pos': array([[ 56.655, -15.962, 226.441],
           [ 55.609, -15.735, 227.429],
           [ 56.227, -15.783, 228.819],
           [ 57.297, -16.359, 229.025]], dtype=float32)},
   {'name': 'SER',
    'abbr': 'S',
    'pos': array([[ 55.544, -15.17 , 229.782],
           [ 56.058, -15.087, 231.141],
           [ 54.973, -15.469, 232.136],
           [ 53.804, -15.105, 231.981]], dtype=float32)},
   {'name': 'LEU',
    'abbr': 'L',
    'pos': array([[ 55.378, -16.219, 233.157],
           [ 54.543, -16.532, 234.306],
           [ 55.253, -16.04 , 235.559],
           [ 56.336, -16.524, 235.902]], dtype=float32)},
   {'name': 'LYS',
    'abbr': 'K',
    'pos': array([[ 54.641, -15.075, 236.237],
           [ 55.231, -14.439, 237.405],
           [ 54.375, -14.74 , 238.625],
           [ 53.147, -14.816, 238.53 ]], dtype=float32)},
   {'name': 'LEU',
    'abbr': 'L',
    'pos': array([[ 55.033, -14.919, 239.768],
           [ 54.364, -15.238, 241.028],
           [ 55.041, -14.435, 242.133],
           [ 56.097, -14.829, 242.639]], dtype=float32)},
   {'name': 'SER',
    'abbr': 'S',
    'pos': array([[ 54.436, -13.31 , 242.501],
           [ 54.956, -12.484, 243.576],
           [ 54.374, -12.925, 244.916],
           [ 53.18 , -13.215, 245.039]], dtype=float32)},
   {'name': 'SER',
    'abbr': 'S',
    'pos': array([[ 55.234, -12.933, 245.935],
           [ 54.889, -13.428, 247.267],
           [ 54.577, -14.924, 247.247],
           [ 53.504, -15.371, 247.657]], dtype=float32)},
   {'name': 'VAL',
    'abbr': 'V',
    'pos': array([[ 55.539, -15.701, 246.742],
           [ 55.338, -17.138, 246.608],
           [ 55.483, -17.831, 247.962],
           [ 56.   , -17.27 , 248.936]], dtype=float32)},
   {'name': 'THR',
    'abbr': 'T',
    'pos': array([[ 55.014, -19.075, 248.016],
           [ 55.068, -19.882, 249.224],
           [ 55.39 , -21.319, 248.843],
           [ 55.857, -21.602, 247.736]], dtype=float32)},
   {'name': 'ALA',
    'abbr': 'A',
    'pos': array([[ 55.151, -22.231, 249.789],
           [ 55.37 , -23.65 , 249.53 ],
           [ 54.318, -24.21 , 248.581],
           [ 54.607, -25.102, 247.775]], dtype=float32)},
   {'name': 'ALA',
    'abbr': 'A',
    'pos': array([[ 53.093, -23.695, 248.657],
           [ 52.013, -24.133, 247.778],
           [ 52.138, -23.607, 246.357],
           [ 51.473, -24.152, 245.466]], dtype=float32)},
   {'name': 'ASP',